### ISSUE TITLE
Does this require Things 3 Desktop app?

### ISSUE THREAD

**Issue by sumant-28** [liamcain/obsidian-things-logbook#19]
I have Things 3 on iPad and iPhone but not Mac because it costs a lot on desktop. I downloaded this plugin a few minutes ago and it doesn't seem to be doing anything. I thought maybe it would ask for my credentials while I was on mobile but I don't know if this app is presumptively desktop only. I can see the reason why it is not doing anything is there is no interfacing between my Obsidian app and my Things account

**Comment by swehba** [comment]
I can't comment definitively as to whether or not Things 3 on the Mac is required, but I assume it is. I can, however, confirm that even with Things 3, there appears to be a problem with the plug in at the moment. See my issue on this. Liam is aware of the problem and is working on it. So, stayed tuned. ;-)

**Comment by sumant-28** [comment]
Hi can you confirm whether there is a now a working prototype? I don't want to make the expensive Obsidian Mac app purchase before finding that out. I can see some indication from the other issues and the log of changes that it is working for some

**Comment by liamcain** [comment]
Hi @sumant-28, sorry I didn't address this post sooner, I'm embarrassingly behind on some plugin issues.

To answer the original question: Yes, this is a desktop only plugin. It periodically fetches your tasks from the Things database on your Mac, so for tasks to appear on your mobile device, they will need to be synced from your desktop first.

As for the issue that @swehba mentioned, that has already been resolved in the latest version.
