### ISSUE TITLE
Option: Don't include a Thing's "notes" field

### ISSUE THREAD

**Issue by adarsh** [liamcain/obsidian-things-logbook#34]
Running on version 0.1.14

I'm a HUGE fan of this plugin, thank you for putting the work in to make it!

I would love an option to **not** include the "notes" field from a Things todo when appending to my daily note.

Often I copy/paste emails in there and they get very long.

I would just delete that text, but the sync is _so good_ that it returns and appends the information anyhow. 

Thank you!

**Comment by IlyasYOY** [comment]
Can I do this? 
Is there anyone working on this issue?

**Comment by liamcain** [comment]
@IlyasYOY Sure, a PR would be appreciated! Thanks 🙏
