### ISSUE TITLE
The latest synchronization will overwrite tasks previously synchronized tasks

### ISSUE THREAD

**Issue by N1ng** [liamcain/obsidian-things-logbook#4]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

In the same daily note, the latest synchronization of the plugin will overwrite tasks written by it before.

### Steps to reproduce
1. Complete some tasks in Things 3.
2. Wait until the synchronization is completed.
3. The completed tasks today is logged in Obsidian daily note section "logbook"
3. Complete some new tasks in Things 3.
4. Wait until another synchronization is completed.
5. The previously synchronized tasks are overwritten.

### Screenshots
Tasks complete today in Things:
![image](https://user-images.githubusercontent.com/9073944/110947473-2b8fea00-837b-11eb-95f9-64243de8e1a9.png)

Tasks logged by plugin in Obsidian:
![image](https://user-images.githubusercontent.com/9073944/110947627-5d08b580-837b-11eb-973e-1cdda37f376e.png)

#### OS

- macOS Big Sur Version 11.2.3

#### Obsidian Version (e.g. v0.10.6)

- Obsidian: v0.11.6
- Plugin: 0.1.6

### Theme (if applicable):

- Minimal Theme
- Hider

**Comment by liamcain** [comment]
Hi @N1ng, good catch and thanks for the detailed bug report! I know what the issue is, I'll have a fix for you soon.

**Comment by N1ng** [comment]
Hi @liamcain , thank you! The logbook plugin is one of my favorite. I am pretty sure that more people will like it. Have a nice weekend!

**Comment by liamcain** [comment]
I just released a new version which fixes this issue. If you lost any data from a bad sync you can easily regenerate it. Just go into your plugin directory (`vault/.obsidian/plugins/things-logbook/`) there should be a file called `data.json`. You can either delete that file completely (this will mean your plugin settings are reset) OR you can open it and remove the `latestSyncTime` key/value pair.
