### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by yoghurtdewdew** [liamcain/obsidian-things-logbook#45]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug
Sync failed
_A clear and concise description of what the bug is._

### Steps to reproduce
⌘P and choose Things Logbook: sync 
3. See error

### Expected behavior
Sync succeed
_A clear and concise description of what you expected to happen_.

### Screenshots
<img width="204" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/31786fe5-bbc4-49bb-be50-a066c45b0201">

<img width="494" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/2816c309-a600-4188-b278-3e93006f55ed">
<img width="767" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/b9850226-e746-40e2-974b-782f158ff843">

_If applicable, add screenshots to help explain your problem._

#### OS
macOS 13.4.1 (c) 
[Windows/macOS/Linux]

#### Obsidian Version (e.g. v0.10.6)
v 1.3.5
`(Settings → About → Current Version)`

### Theme (if applicable):
minimal
_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by pwflint** [comment]
In a recent update Things changed the path for main database. There is a similar issue discussed in #44. 

To work around in macOS:

1. Navigate to `~/Library/Group Containers/JLMPQHK86H.com.culturedcode.ThingsMac` and open the `Readme - Database moved (<date>)` file. Copy the path in the file.
2. Open the `main.js` file in `.obsidian/plugins/things-logbook` in the affected vault.
3. Find "THINGS_DB_PATH =" in the `.js` file and paste the new path from the Readme file.
4. Restart Obsidian, logbook plugin can now sync.

Additional comments that might be helpful [here](https://github.com/liamcain/obsidian-things-logbook/issues/44#issuecomment-1510383801).

**Comment by yoghurtdewdew** [comment]
That's really helpful! Thanks so much it's working now!

But I found some new different problems and have a new question: 

As you can see it is successful to sync in 2 daily notes now. But in Things I found 2+ date. Is this normal?

Another problem is that the project is not showed as the parents of there tasks, and the titles were not shown. I wish there would be some perfect **indentation for area-project(and its description as notes)-titles(⚠️)-tasks(and its notes) levels**.

My suggested format:
area: format of title with a lower lever than _section heading_;
project: format of todo for completed/incompleted project, and **format of list for unchecked project**;
titles: format of list
tasks: format of todo for completed/incompleted tasks

And another question is that: if I changed the _section heading_ and _canceled mark_ in settings, would it sync duplicate things or sync the old versions to new ones？

<img width="404" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/29366f69-42c6-4851-976e-a1c3bbdcb1ed">
<img width="454" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/f6779791-f362-42e5-b41c-37189f21a3df">
<img width="264" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/0dd7318a-2a3a-48e5-a652-3915bd52751c">
<img width="457" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/b3a72d2b-ddbb-43e4-876d-c15769b97db7">
<img width="361" alt="image" src="https://github.com/liamcain/obsidian-things-logbook/assets/63794438/7e982f67-0ffc-4b9b-ab5d-ad5440a3f94e">

**Comment by pwflint** [comment]
If you are finding new/different issues I suggest filing a new issue or feature request.

**Comment by yoghurtdewdew** [comment]
Thanks for your kind advice and I have put them in new issues.

Thanks for your great creativity and awesome plugins!
