### ISSUE TITLE
Reset the synced items to new format or re-synced.

### ISSUE THREAD

**Issue by yoghurtdewdew** [liamcain/obsidian-things-logbook#48]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The feature might have already been included 😄

**Is your feature request related to a problem? Please describe.**

I searched 'reset' and found #4 but I am not sure if they will be related.

**Describe the solution you'd like**

I have had a question: if I changed the section heading and canceled mark in settings, would it sync duplicate things or sync the old versions to new ones？

Now it seemed like the synced items would not be changed again.

So will there be an option to clean all the have synced items and re-synced again?

Otherwise, if when I change the section heading and canceled mark in plugin settings, the synced items would be re-format or re-synced, that would be better!

**Describe alternatives you've considered**

Search and replace the old synced items to new format manually.

**Additional context**

**Comment by liamcain** [comment]
A reset button has been added to settings in v0.2
