### ISSUE TITLE
Upon initial sync the Things Logs overwrite the entire daily file rather than appending it.

### ISSUE THREAD

**Issue by leoplanet** [liamcain/obsidian-things-logbook#6]
> **Before Submitting:** Double-check that you are running the latest version of the plugin. The bug might have already been fixed 😄

### Describe the bug

When the plugin runs for the first time, instead of appending the Things logs to the existing daily notes, it overwrites the entire note.

### Steps to reproduce

1. Install Plugin
2. Configure plugin with defaults
3. Run plugin

### Expected behavior

Many notes are created that do not already exist
Existing daily notes get the Things log appended to them at the bottom

### Screenshots

_If applicable, add screenshots to help explain your problem._

#### Mac OSX Big Sur 11.2.3 

[Windows/macOS/Linux]

#### Obsidian Version 0.11.7

`(Settings → About → Current Version)`

### Theme (if applicable):

_If the bug is visual, please provide the name of the Community Theme you're using._

**Comment by liamcain** [comment]
Hi @leoplanet, I'm sorry if this bug caused you any issues. Hopefully it didn't result in any serious data loss for you or other users.

The last version made a bad assumption that the Logbook heading will always exist in the daily note, which is definitely not the case.

I just published v0.1.8 to fix the issue.

**Comment by pmbauer** [comment]
Thanks so much for this fix and the sync plugin!
